Lesson2
sinitsa2001/dj_git1 pull request #1
Opened 2020-12-07 15:38 UTC by sinitsa2001

2020-12-08 07:40 UTC, Vokler requested changes
Маленькое замечание. Исправьте и я оценю вашу работу на GeekBrains

2020-12-08 07:40 UTC, Vokler commented on mainapp/views.py
> +    context = {
Добавьте в context список с продуктами, чтобы в products.html генерировать продукты динамически, заключив их в блок for

2020-12-08 20:33 UTC, sinitsa2001 commented on mainapp/views.py
> +    context = {
Сделал то что просили. Только не полностью .ибо как то коряво получается. Вроде отражается на странице то что надо = но все стили куда то улетели...не понимаю как прицепить.  Сделал только два продукта  - чтобы другие не "ломать" -= если правильно =остальные допилю... но ...как говориться -= терзают смутные сомнения

2020-12-09 11:12 UTC, Vokler requested changes

2020-12-09 11:12 UTC, Vokler commented on mainapp/templates/mainapp/products.html
> +{% load static %}
Тут неверно, нужно `{% load staticfiles %}`
Возмодно из-за этого стили и не отображаеются

2020-12-09 11:12 UTC, Vokler commented on mainapp/templates/mainapp/index.html
> +{% load static %}
Тут тоже нужно {% load staticfiles %}

2020-12-09 12:12 UTC, sinitsa2001 commented on mainapp/templates/mainapp/index.html
> +{% load static %}
Все исправил. Изменения залил.
По стилистике, кстати, = {% load staticfiles %} -=  не решил вопрос. Надо разбираться...но уже нет времени. надо дз 3 делать и сдавать.

2021-01-14 20:53 UTC, closed without merging

2021-01-14 20:53 UTC, sinitsa2001 commented
end